services:
  horkos-api:
    container_name: horkos-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5198:5198"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./HorkosAPI/HorkosAPI:/app/HorkosAPI/HorkosAPI
    depends_on:
      horkos-db:
        condition: service_healthy

  horkos-db:
    container_name: horkos-db
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U horkos"]
      interval: 5s
      timeout: 5s
      retries: 5
